Run the tests for the plotting function
Shortly after the baseline image was generated, one of your colleagues modified the plotting function. You have to run the tests in order to check whether the function still works as expected.
Remember that the tests were housed in a test class TestGetPlotForBestFitLine in the test module visualization/test_plots.py.


Run the tests in this test class in the console. Because it's a shell console and not an IPython one, you don't need to use the ! at the beginning of your command. You should see two failures.

repl:~/workspace$ pytest -k "TestGetPlotForBestFitLine" --mpl

================================= test session starts =================================
platform linux -- Python 3.6.7, pytest-5.2.2, py-1.8.1, pluggy-0.12.0
Matplotlib: 3.1.1
Freetype: 2.6.1
rootdir: /home/repl/workspace
plugins: mock-1.11.2, mpl-0.10
collected 26 items / 24 deselected / 2 selected                                       

project/tests/visualization/test_plots.py FF                                    [100%]



====================================== FAILURES =======================================
_________________ TestGetPlotForBestFitLine.test_plot_for_linear_data _________________
Error: Image files did not match.
  RMS Value: 11.191347848524174
  Expected:  
    /tmp/tmp4hjxog1u/baseline-test_plot_for_linear_data.png
  Actual:    
    /tmp/tmp4hjxog1u/test_plot_for_linear_data.png
  Difference:
    /tmp/tmp4hjxog1u/test_plot_for_linear_data-failed-diff.png
  Tolerance: 
    2
_____________ TestGetPlotForBestFitLine.test_plot_for_almost_linear_data ______________
Error: Image files did not match.
  RMS Value: 11.191347848524174
  Expected:  
    /tmp/tmpk588tkf_/baseline-test_plot_for_almost_linear_data.png
  Actual:    
    /tmp/tmpk588tkf_/test_plot_for_almost_linear_data.png
  Difference:
    /tmp/tmpk588tkf_/test_plot_for_almost_linear_data-failed-diff.png
  Tolerance: 
    2
========================== 2 failed, 24 deselected in 1.86s ==========================



Unfortunately, your colleague has done something horrible and both tests are failing. In the test result report, you probably saw that pytest saved the actual plot, the baseline and the pixelwise difference to a temporary folder. In the next exercise, you will look at these images and try to fix the wreck that your colleague has caused.
